spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: EmTxF564kL
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    rest:
      base-path: /api/rest
